.TH BASECONV "1" "March 2026" "baseconv v1.0.0" "User Commands"
.SH NAME
baseconv \- convert integer number bases
.SH SYNOPSIS
.SY
.B baseconv
[\fI\,OPTION\/\fR]... \-i \fIIBASE\fR \-o \fIOBASE\fR [\fI\,NUMBER\/\fR]...
.YS
.SH DESCRIPTION
.B baseconv
converts integer numbers from an input number base
.I IBASE
to an output base \fIOBASE\fR.
Non-integer numbers are not handled.
.TP
If no \fINUMBER\fRs are specified on the command line, read them from standard input.
.SH OPTIONS
Mandatory options to long options are mandatory for short options too.
.TP
\fB\-i\fR, \fB\-\-input-base\fR=\fI\,IBASE\/\fR
Convert from base \fIIBASE\fR.
.I IBASE
may be any base supported by GNU MP.
.br
\- Bases [2, 36] use integers, then letters (non-case-sensititve).
.br
\- Bases [37, 62] use integers, upper-case letters, then lower-case letters.
.TP
\fB\-o\fR, \fB\-\-output-base\fR=\fI\,OBASE\/\fR
Convert to base \fIOBASE\fR.
.I OBASE
may be any base supported by GNU MP.
.br
\- Bases [2, 36] use integers, then upper-case letters.
.br
\- Bases [-36, -2] use integers, then lower-case letters.
.br
\- Bases [37, 62] use integers, upper-case letters, then lower-case letters.
.TP
\fB\-l\fR, \fB\-\-loose\-exit\fR
Change the behavior of the exit status.
Normally, the program will exit non-zero if any invalid input is provided.
This flag will change the behavior such that the program will only exit non-zero if a fatal error is encountered.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable the printing of \fINUMBER\fR in the original base, before the converted number.
This is probably more useful for scripts, but really probably is never going to be used.
.TP
\fB\-s\fR, \fB\-\-silent\fR
Supress all error messages.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a short help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.
.PP
.SH AUTHOR
Written by Jack R. Uteg.
.SH COPYRIGHT
Copyright \(co 2026 Jack Renton Uteg.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.TP
\fBcollatz(1)\fR, \fBfib(1)\fR, \fBfactor(1)\fR, \fBpoly(1)\fR, \fBprime(1)\fR
